/*******************************************************************************
 * Copyright 2019-2021 Microchip FPGA Embedded Systems Solutions.
 *
 * SPDX-License-Identifier: MIT
 *
 * @file hw_mpu_trace.h
 * @author Microchip-FPGA Embedded Systems Solutions
 *
 * Generated using Libero version: 2021.1
 * Libero design name: ICICLE_MSS
 * MPFS part number used in design: MPFS250T_ES
 * Date generated by Libero: 04-11-2021_22:30:25
 * Format version of XML description: 0.5.3
 * PolarFire SoC Configuration Generator version: 0.4.1
 *
 * Note 1: This file should not be edited. If you need to modify a parameter,
 * without going through the Libero flow or editing the associated xml file,
 * the following method is recommended:
 *   1. edit the file platform//config//software//mpfs_hal//mss_sw_config.h
 *   2. define the value you want to override there. (Note: There is a
 *      commented example in mss_sw_config.h)
 * Note 2: The definition in mss_sw_config.h takes precedence, as
 * mss_sw_config.h is included prior to the hw_mpu_trace.h in the hal
 * (see platform//mpfs_hal//mss_hal.h)
 *
 */

#ifndef HW_MPU_TRACE_H_
#define HW_MPU_TRACE_H_


#ifdef __cplusplus
extern  "C" {
#endif

#if !defined (LIBERO_SETTING_TRACE_MPU_CFG_PMP0)
/*mpu setup register, 64 bits */
#define LIBERO_SETTING_TRACE_MPU_CFG_PMP0    0x1F00000FFFFFFFFFULL
    /* PMP                               [0:38]  RW value= 0xFFFFFFFFF */
    /* RESERVED                          [38:18] RW value= 0x0 */
    /* MODE                              [56:8]  RW value= 0x1F */
#endif
#if !defined (LIBERO_SETTING_TRACE_MPU_CFG_PMP1)
/*mpu setup register, 64 bits */
#define LIBERO_SETTING_TRACE_MPU_CFG_PMP1    0x1F00000FFFFFFFFFULL
    /* PMP                               [0:38]  RW value= 0xFFFFFFFFF */
    /* RESERVED                          [38:18] RW value= 0x0 */
    /* MODE                              [56:8]  RW value= 0x1F */
#endif

#ifdef __cplusplus
}
#endif


#endif /* #ifdef HW_MPU_TRACE_H_ */

