/*******************************************************************************
 * Copyright 2023 Microchip FPGA Embedded Systems Solutions.
 * Script version: develop-1.0.017
 * Register specification version: v1.0
 * Register specification Date: 2023-03-14 00:00:00
 * Note: Autogenerated headers from IP supplied xlsx
 * Author: Embedded Software
 */

#ifndef MIV_IHC_RESET_DEFAULTS_REGS_H_
#define MIV_IHC_RESET_DEFAULTS_REGS_H_
#ifdef __cplusplus
extern "C" {
#endif

// #define RESERVED                                       ((uint32_t)(0x00000000UL))

/* miv_IHC_reset_defaults */

#ifdef __cplusplus
}
#endif

#endif /* MIV_IHC_RESET_DEFAULTS_H_ */