/*******************************************************************************
 * Copyright 2023 Microchip FPGA Embedded Systems Solutions.
 * Script version: develop-1.0.020
 * Register specification version: v0.1
 * Register specification Date: 2023-09-11 00:00:00
 * Note: Autogenerated headers from IP supplied xlsx
 * Author: Embedded Software
 */

#ifndef UINT_32_BIT_MASKS_REGS_H_
#define UINT_32_BIT_MASKS_REGS_H_
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#ifndef BIT
#define BIT(n)          (1U << (n))
#endif

#ifndef GENMASK
#define GENMASK(h, l) \
    (((~0U) << (l)) & (~0U >> (31 - (h))))
#endif

#ifdef __cplusplus
}
#endif

#endif /* UINT_32_BIT_MASKS_H_ */