/*******************************************************************************
 * Copyright 2020 Microchip Corporation.
 * 
 * SPDX-License-Identifier: MIT
 * 
 * @file hw_ddr_segs.h
 * @author Microchip-FPGA Embedded Systems Solutions
 * 
 * Generated using Libero version: 10.0.0
 * Libero design name: test design
 * MPFS part number used in design: M2PFS250T_ES
 * Date generated by Libero: 2020-01-02 16:48:54
 * Format version of XML description: 0.3.1
 * PolarFire SoC Configuration Generator version: 0.3.2
 * 
 * Note 1: This file should not be edited. If you need to modify a parameter,
 * without going through the Libero flow or editing the associated xml file,
 * the following method is recommended:
 *   1. edit the file platform//config//software//mpfs_hal//mss_sw_config.h
 *   2. define the value you want to override there. (Note: There is a 
 *      commented example in mss_sw_config.h)
 * Note 2: The definition in mss_sw_config.h takes precedence, as 
 * mss_sw_config.h is included prior to the hw_ddr_segs.h in the hal 
 * (see platform//mpfs_hal//mss_hal.h)
 *
 */ 

#ifndef HW_DDR_SEGS_H_
#define HW_DDR_SEGS_H_


#ifdef __cplusplus
extern  "C" {
#endif

#if !defined (LIBERO_SETTING_SEG0_0)
/*Cached access at 0x00_8000_0000 (-0x80+0x00) */ 
#define LIBERO_SETTING_SEG0_0    0x00007F80UL
    /* ADDRESS_OFFSET                    [0:15]  RW value= 0x7F80 */ 
    /* RESERVED                          [15:16] RW value= 0x0 */ 
    /* LOCKED                            [31:1]  RW value= 0x0 */ 
#endif
#if !defined (LIBERO_SETTING_SEG0_1)
/*Cached access at 0x10_0000_000 */ 
#define LIBERO_SETTING_SEG0_1    0x00007000UL
    /* ADDRESS_OFFSET                    [0:15]  RW value= 0x7000 */ 
    /* RESERVED                          [15:16] RW value= 0x0 */ 
    /* LOCKED                            [31:1]  RW value= 0x0 */ 
#endif
#if !defined (LIBERO_SETTING_SEG0_2)
/*not used */ 
#define LIBERO_SETTING_SEG0_2    0x00000000UL
    /* ADDRESS_OFFSET                    [0:15]  RW value= 0x0 */ 
    /* RESERVED                          [15:16] RW value= 0x0 */ 
    /* LOCKED                            [31:1]  RW value= 0x0 */ 
#endif
#if !defined (LIBERO_SETTING_SEG0_3)
/*not used */ 
#define LIBERO_SETTING_SEG0_3    0x00000000UL
    /* ADDRESS_OFFSET                    [0:15]  RW value= 0x0 */ 
    /* RESERVED                          [15:16] RW value= 0x0 */ 
    /* LOCKED                            [31:1]  RW value= 0x0 */ 
#endif
#if !defined (LIBERO_SETTING_SEG0_4)
/*not used */ 
#define LIBERO_SETTING_SEG0_4    0x00000000UL
    /* ADDRESS_OFFSET                    [0:15]  RW value= 0x0 */ 
    /* RESERVED                          [15:16] RW value= 0x0 */ 
    /* LOCKED                            [31:1]  RW value= 0x0 */ 
#endif
#if !defined (LIBERO_SETTING_SEG0_5)
/*not used */ 
#define LIBERO_SETTING_SEG0_5    0x00000000UL
    /* ADDRESS_OFFSET                    [0:15]  RW value= 0x0 */ 
    /* RESERVED                          [15:6]  RW value= 0x0 */ 
    /* LOCKED                            [31:1]  RW value= 0x0 */ 
#endif
#if !defined (LIBERO_SETTING_SEG0_6)
/*not used */ 
#define LIBERO_SETTING_SEG0_6    0x00000000UL
    /* ADDRESS_OFFSET                    [0:15]  RW value= 0x0 */ 
    /* RESERVED                          [15:16] RW value= 0x0 */ 
    /* LOCKED                            [31:1]  RW value= 0x0 */ 
#endif
#if !defined (LIBERO_SETTING_SEG0_7)
/*not used */ 
#define LIBERO_SETTING_SEG0_7    0x00000000UL
    /* ADDRESS_OFFSET                    [0:15]  RW value= 0x0 */ 
    /* RESERVED                          [15:16] RW value= 0x0 */ 
    /* LOCKED                            [31:1]  RW value= 0x0 */ 
#endif
#if !defined (LIBERO_SETTING_SEG1_0)
/*not used */ 
#define LIBERO_SETTING_SEG1_0    0x00000000UL
    /* ADDRESS_OFFSET                    [0:15]  RW value= 0x0 */ 
    /* RESERVED                          [15:16] RW value= 0x0 */ 
    /* LOCKED                            [31:1]  RW value= 0x0 */ 
#endif
#if !defined (LIBERO_SETTING_SEG1_1)
/*not used */ 
#define LIBERO_SETTING_SEG1_1    0x00000000UL
    /* ADDRESS_OFFSET                    [0:15]  RW value= 0x0 */ 
    /* RESERVED                          [15:16] RW value= 0x0 */ 
    /* LOCKED                            [31:1]  RW value= 0x0 */ 
#endif
#if !defined (LIBERO_SETTING_SEG1_2)
/*Non-Cached access at 0x00_c000_0000 */ 
#define LIBERO_SETTING_SEG1_2    0x00007F40UL
    /* ADDRESS_OFFSET                    [0:15]  RW value= 0x7F40 */ 
    /* RESERVED                          [15:16] RW value= 0x0 */ 
    /* LOCKED                            [31:1]  RW value= 0x0 */ 
#endif
#if !defined (LIBERO_SETTING_SEG1_3)
/*Non-Cached access at 0x14_0000_0000 */ 
#define LIBERO_SETTING_SEG1_3    0x00006C00UL
    /* ADDRESS_OFFSET                    [0:15]  RW value= 0x6C00 */ 
    /* RESERVED                          [15:16] RW value= 0x0 */ 
    /* LOCKED                            [31:1]  RW value= 0x0 */ 
#endif
#if !defined (LIBERO_SETTING_SEG1_4)
/*Non-Cached WCB access at 0x00_d000_0000 */ 
#define LIBERO_SETTING_SEG1_4    0x00007F30UL
    /* ADDRESS_OFFSET                    [0:15]  RW value= 0x7F30 */ 
    /* RESERVED                          [15:16] RW value= 0x0 */ 
    /* LOCKED                            [31:1]  RW value= 0x0 */ 
#endif
#if !defined (LIBERO_SETTING_SEG1_5)
/*Non-Cached WCB 0x18_0000_0000 */ 
#define LIBERO_SETTING_SEG1_5    0x00006800UL
    /* ADDRESS_OFFSET                    [0:15]  RW value= 0x6800 */ 
    /* RESERVED                          [15:6]  RW value= 0x0 */ 
    /* LOCKED                            [31:1]  RW value= 0x0 */ 
#endif
#if !defined (LIBERO_SETTING_SEG1_6)
/*Trace - Trace not in use here so can be left as 0 */ 
#define LIBERO_SETTING_SEG1_6    0x00000000UL
    /* ADDRESS_OFFSET                    [0:15]  RW value= 0x0 */ 
    /* RESERVED                          [15:16] RW value= 0x0 */ 
    /* LOCKED                            [31:1]  RW value= 0x0 */ 
#endif
#if !defined (LIBERO_SETTING_SEG1_7)
/*not used */ 
#define LIBERO_SETTING_SEG1_7    0x00000000UL
    /* ADDRESS_OFFSET                    [0:15]  RW value= 0x0 */ 
    /* RESERVED                          [15:16] RW value= 0x0 */ 
    /* LOCKED                            [31:1]  RW value= 0x0 */ 
#endif

#ifdef __cplusplus
}
#endif


#endif /* #ifdef HW_DDR_SEGS_H_ */

